## FASE 2 — **Data Cleaning y Data Quality**

Objetivo: Verificar integridad los datos y utilizarlos para construir una base temporal consistente

Esta fase se concentrará en: estructura, tipos, fechas, identificadores, nulos, duplicados, valores inválidos, rangos, consistencia temporal y consistencia entre tablas.

In [2]:
import pandas as pd

In [3]:
df_errors = pd.read_csv("https://raw.githubusercontent.com/No-Country-simulation/S08-26-EQUIPO-24/refs/heads/main/data/raw/PdM_errors.csv")
df_failures = pd.read_csv("https://raw.githubusercontent.com/No-Country-simulation/S08-26-EQUIPO-24/refs/heads/main/data/raw/PdM_failures.csv")
df_machines = pd.read_csv("https://raw.githubusercontent.com/No-Country-simulation/S08-26-EQUIPO-24/refs/heads/main/data/raw/PdM_machines.csv")
df_maint = pd.read_csv("https://raw.githubusercontent.com/No-Country-simulation/S08-26-EQUIPO-24/refs/heads/main/data/raw/PdM_maint.csv")
df_telemetry = pd.read_csv("https://raw.githubusercontent.com/No-Country-simulation/S08-26-EQUIPO-24/refs/heads/main/data/raw/PdM_telemetry.csv")

### 1. Verificación Inicial

#### 1.1. Revisión Inicial y Conversión de Tipos

Los aporte y verificaciones iniciales son fundamentales para asegurar que los datos estén en el formato correcto antes de proceder con un análisis más profundo:

In [4]:
df_errors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3919 entries, 0 to 3918
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   3919 non-null   object
 1   machineID  3919 non-null   int64
 2   errorID    3919 non-null   object
dtypes: int64(1), object(2)
memory usage: 92.0+ KB

In [5]:
df_errors.head()

              datetime  machineID errorID
0  2015-01-03 07:00:00          1  error1
1  2015-01-03 20:00:00          1  error3
2  2015-01-04 06:00:00          1  error5
3  2015-01-10 15:00:00          1  error4
4  2015-01-22 10:00:00          1  error4

In [6]:
df_failures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   761 non-null    object
 1   machineID  761 non-null    int64
 2   failure    761 non-null    object
dtypes: int64(1), object(2)
memory usage: 18.0+ KB

In [7]:
df_machines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   machineID  100 non-null    int64
 1   model      100 non-null    object
 2   age        100 non-null    int64
dtypes: int64(2), object(1)
memory usage: 2.5+ KB

In [8]:
df_maint.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   3286 non-null   object
 1   machineID  3286 non-null   int64
 2   comp       3286 non-null   object
dtypes: int64(1), object(2)
memory usage: 77.1+ KB

In [9]:
df_telemetry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876100 entries, 0 to 876099
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   datetime   876100 non-null  object
 1   machineID  876100 non-null  int64
 2   volt       876100 non-null  float64
 3   rotate     876100 non-null  float64
 4   pressure   876100 non-null  float64
 5   vibration  876100 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 40.1+ MB

In [10]:
# Revisión inicial de info() y head() para todos los DataFrames
print("### Revisión de Estructura y Primeras Filas ###")

dfs = {
    'df_errors': df_errors,
    'df_failures': df_failures,
    'df_machines': df_machines,
    'df_maint': df_maint,
    'df_telemetry': df_telemetry
}

for name, df in dfs.items():
    print(f"\n--- {name}.head() ---")
    display(df.head())
    print(f"\n--- {name}.info() ---")
    df.info()

### Revisión de Estructura y Primeras Filas ###

--- df_errors.head() ---

              datetime  machineID errorID
0  2015-01-03 07:00:00          1  error1
1  2015-01-03 20:00:00          1  error3
2  2015-01-04 06:00:00          1  error5
3  2015-01-10 15:00:00          1  error4
4  2015-01-22 10:00:00          1  error4

--- df_errors.info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3919 entries, 0 to 3918
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   3919 non-null   object
 1   machineID  3919 non-null   int64
 2   errorID    3919 non-null   object
dtypes: int64(1), object(2)
memory usage: 92.0+ KB

--- df_failures.head() ---

              datetime  machineID failure
0  2015-01-05 06:00:00          1   comp4
1  2015-03-06 06:00:00          1   comp1
2  2015-04-20 06:00:00          1   comp2
3  2015-06-19 06:00:00          1   comp4
4  2015-09-02 06:00:00          1   comp4

--- df_failures.info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 761 entries, 0 to 760
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   761 non-null    object
 1   machineID  761 non-null    int64
 2   failure    761 non-null    object
dtypes: int64(1), object(2)
memory usage: 18.0+ KB

--- df_machines.head() ---

   machineID   model  age
0          1  model3   18
1          2  model4    7
2          3  model3    8
3          4  model3    7
4          5  model3    2

--- df_machines.info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   machineID  100 non-null    int64
 1   model      100 non-null    object
 2   age        100 non-null    int64
dtypes: int64(2), object(1)
memory usage: 2.5+ KB

--- df_maint.head() ---

              datetime  machineID   comp
0  2014-06-01 06:00:00          1  comp2
1  2014-07-16 06:00:00          1  comp4
2  2014-07-31 06:00:00          1  comp3
3  2014-12-13 06:00:00          1  comp1
4  2015-01-05 06:00:00          1  comp4

--- df_maint.info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3286 entries, 0 to 3285
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   datetime   3286 non-null   object
 1   machineID  3286 non-null   int64
 2   comp       3286 non-null   object
dtypes: int64(1), object(2)
memory usage: 77.1+ KB

--- df_telemetry.head() ---

,datetime,machineID,volt,rotate,pressure,vibration
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847
3,2015-01-01 09:00:00,1,162.462833,346.149335,109.248561,41.122144
4,2015-01-01 10:00:00,1,157.610021,435.376873,111.886648,25.990511

--- df_telemetry.info() ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 876100 entries, 0 to 876099
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   datetime   876100 non-null  object
 1   machineID  876100 non-null  int64
 2   volt       876100 non-null  float64
 3   rotate     876100 non-null  float64
 4   pressure   876100 non-null  float64
 5   vibration  876100 non-null  float64
dtypes: float64(4), int64(1), object(1)
memory usage: 40.1+ MB

#### 1.2. Conversión de Columnas (fecha) `datetime` a Formato `datetime`

Es crucial que las columnas de fecha y hora estén en el tipo de dato correcto para permitir operaciones temporales y ordenamiento adecuado. Las revisiones iniciales muestran que estaban como `object`.

In [11]:
# Convertir las columnas 'datetime' a tipo datetime
df_errors['datetime'] = pd.to_datetime(df_errors['datetime'])
df_failures['datetime'] = pd.to_datetime(df_failures['datetime'])
df_maint['datetime'] = pd.to_datetime(df_maint['datetime'])
df_telemetry['datetime'] = pd.to_datetime(df_telemetry['datetime'])

print("Columnas 'datetime' convertidas a tipo `datetime` exitosamente.")

Columnas 'datetime' convertidas a tipo `datetime` exitosamente.

#### 1.3. Verificación de Duplicados

Detectar y manejar filas duplicadas es un paso esencial para asegurar la integridad del dataset y evitar conteos erróneos o sesgos en el análisis.

In [12]:
print(df_errors.duplicated().sum())
print(df_failures.duplicated().sum())
print(df_machines.duplicated().sum())
print(df_maint.duplicated().sum())
print(df_telemetry.duplicated().sum())

0
0
0
0
0

In [13]:
# Verificar filas duplicadas en cada DataFrame
print("*** Conteo de Duplicados por DataFrame ***")
print(f"df_errors duplicados: {df_errors.duplicated().sum()}")
print(f"df_failures duplicados: {df_failures.duplicated().sum()}")
print(f"df_machines duplicados: {df_machines.duplicated().sum()}")
print(f"df_maint duplicados: {df_maint.duplicated().sum()}")
print(f"df_telemetry duplicados: {df_telemetry.duplicated().sum()}")

*** Conteo de Duplicados por DataFrame ***
df_errors duplicados: 0
df_failures duplicados: 0
df_machines duplicados: 0
df_maint duplicados: 0
df_telemetry duplicados: 0

### Observaciones de análisis inicial:

*   **Tipos de Datos:** La conversión de `datetime` a tipo fecha y hora fue exitosa, lo cual es fundamental.
*   **Duplicados:** No se encontraron filas completamente duplicadas en ninguno de los DataFrames, lo que es un buen punto de partida para la calidad de los datos.

### 2. Validación de las cinco fuentes del dataset Azure PdM

Validación detallada de cada uno de los cinco DataFrames, según criterios definidos en la documentación.

#### 2.1 `df_telemetry`

La telemetría es la fuente principal que muestra datos de sensores, con mediciones horarias para cada máquina.

In [14]:
#Descripción de datos, verificar valores nulos y valores únicos
print("--- df_telemetry: Descripción Estadística ---")
display(df_telemetry.describe())

print("--- df_telemetry: Conteo de Valores Nulos ---")
display(df_telemetry.isnull().sum())

print("--- df_telemetry: Unicidad de machineID ---")
print(f"Número de machineID únicos: {df_telemetry['machineID'].nunique()}")

--- df_telemetry: Descripción Estadística ---

,datetime,machineID,volt,rotate,pressure,vibration
count,876100,876100.000000,876100.000000,876100.000000,876100.000000,876100.000000
mean,2015-07-02 18:00:00,50.500000,170.777736,446.605119,100.858668,40.385007
min,2015-01-01 06:00:00,1.000000,97.333604,138.432075,51.237106,14.877054
25%,2015-04-02 12:00:00,25.750000,160.304927,412.305714,93.498181,36.777299
50%,2015-07-02 18:00:00,50.500000,170.607338,447.558150,100.425559,40.237247
75%,2015-10-02 00:00:00,75.250000,181.004493,482.176600,107.555231,43.784938
max,2016-01-01 06:00:00,100.000000,255.124717,695.020984,185.951998,76.791072
std,NaN,28.866087,15.509114,52.673886,11.048679,5.370361

--- df_telemetry: Conteo de Valores Nulos ---

datetime     0
machineID    0
volt         0
rotate       0
pressure     0
vibration    0
dtype: int64

--- df_telemetry: Unicidad de machineID ---
Número de machineID únicos: 100

**Observaciones `df_telemetry`:**

*   **Nulos:** No hay valores nulos, lo cual es excelente.
*   **Estadísticas Descriptivas:** Los rangos (`min`, `max`) y cuartiles para `volt`, `rotate`, `pressure`, `vibration` parecen razonables y no muestran anomalías obvias a primera vista. Los valores de `machineID` son enteros y cubren 100 máquinas únicas.
*   **machineID:** Todas las máquinas registradas tienen telemetría.

(continuar segun documentación sugerida)

#### 2.2 `df_errors`

Esta tabla registra eventos de error u alarma, son indicadores de problemas operativos.

**Observaciones `df_errors`:**

#### 2.3 `df_failures`

Esta tabla registra las fallas reales que resultaron en reemplazos de componentes. Es fundamental para definir nuestro objetivo de predicción.

**Observaciones `df_failures`:**